/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatRouteImport } from './routes/what'
import { Route as CenterAbsoluteRouteImport } from './routes/_centerAbsolute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestiIndexRouteImport } from './routes/testi.index'
import { Route as CenterAbsoluteWhyRouteImport } from './routes/_centerAbsolute.why'
import { Route as CenterAbsoluteHowRouteImport } from './routes/_centerAbsolute.how'

const WhatRoute = WhatRouteImport.update({
  id: '/what',
  path: '/what',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterAbsoluteRoute = CenterAbsoluteRouteImport.update({
  id: '/_centerAbsolute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestiIndexRoute = TestiIndexRouteImport.update({
  id: '/testi/',
  path: '/testi/',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterAbsoluteWhyRoute = CenterAbsoluteWhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => CenterAbsoluteRoute,
} as any)
const CenterAbsoluteHowRoute = CenterAbsoluteHowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => CenterAbsoluteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/what': typeof WhatRoute
  '/how': typeof CenterAbsoluteHowRoute
  '/why': typeof CenterAbsoluteWhyRoute
  '/testi': typeof TestiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/what': typeof WhatRoute
  '/how': typeof CenterAbsoluteHowRoute
  '/why': typeof CenterAbsoluteWhyRoute
  '/testi': typeof TestiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_centerAbsolute': typeof CenterAbsoluteRouteWithChildren
  '/what': typeof WhatRoute
  '/_centerAbsolute/how': typeof CenterAbsoluteHowRoute
  '/_centerAbsolute/why': typeof CenterAbsoluteWhyRoute
  '/testi/': typeof TestiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/what' | '/how' | '/why' | '/testi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/what' | '/how' | '/why' | '/testi'
  id:
    | '__root__'
    | '/'
    | '/_centerAbsolute'
    | '/what'
    | '/_centerAbsolute/how'
    | '/_centerAbsolute/why'
    | '/testi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenterAbsoluteRoute: typeof CenterAbsoluteRouteWithChildren
  WhatRoute: typeof WhatRoute
  TestiIndexRoute: typeof TestiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what': {
      id: '/what'
      path: '/what'
      fullPath: '/what'
      preLoaderRoute: typeof WhatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_centerAbsolute': {
      id: '/_centerAbsolute'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CenterAbsoluteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testi/': {
      id: '/testi/'
      path: '/testi'
      fullPath: '/testi'
      preLoaderRoute: typeof TestiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_centerAbsolute/why': {
      id: '/_centerAbsolute/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof CenterAbsoluteWhyRouteImport
      parentRoute: typeof CenterAbsoluteRoute
    }
    '/_centerAbsolute/how': {
      id: '/_centerAbsolute/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof CenterAbsoluteHowRouteImport
      parentRoute: typeof CenterAbsoluteRoute
    }
  }
}

interface CenterAbsoluteRouteChildren {
  CenterAbsoluteHowRoute: typeof CenterAbsoluteHowRoute
  CenterAbsoluteWhyRoute: typeof CenterAbsoluteWhyRoute
}

const CenterAbsoluteRouteChildren: CenterAbsoluteRouteChildren = {
  CenterAbsoluteHowRoute: CenterAbsoluteHowRoute,
  CenterAbsoluteWhyRoute: CenterAbsoluteWhyRoute,
}

const CenterAbsoluteRouteWithChildren = CenterAbsoluteRoute._addFileChildren(
  CenterAbsoluteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenterAbsoluteRoute: CenterAbsoluteRouteWithChildren,
  WhatRoute: WhatRoute,
  TestiIndexRoute: TestiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
